spring.application.name=rescan-api
spring.servlet.multipart.enabled=false
server.error.include-message=never
management.endpoints.web.exposure.include=health
spring.jackson.serialization.write-dates-as-timestamps=false
